### PR TITLE
Attempt to document the current state of affairs in the README

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by abe-101** [comment]
I'm confused why the need for a seporate repo just for the docs
Isn't the source code for the [docs](https://github.com/dj-stripe/dj-stripe/tree/master/docs) in the main [dj-stripe](https://github.com/dj-stripe/dj-stripe) repo
if so why not just have a GH action build and deploy the docs?

**Comment by czue** [comment]
There's a very long discussion on this topic here: https://github.com/dj-stripe/dj-stripe/issues/1841

For what it's worth, I and many others agree with you, but there are some challenges in getting things to that state.

**Comment by abe-101** [comment]
@jleclanche 
can you trigger  "Build and deploy docs"  workflow so i can see the failed logs
currently it was last run over a year ago and the logs are no longer available

https://github.com/dj-stripe/dj-stripe.github.io/actions/workflows/ci.yml

**Comment by abe-101** [comment]
@czue Appriciate you talking the time to add the steps to get this site running locally
Question: when you build it, does it have the styling like dj-stripe.dev does?

**Comment by czue** [comment]
>  Question: when you build it, does it have the styling like dj-stripe.dev does?

No: https://github.com/dj-stripe/dj-stripe/issues/1841#issuecomment-1737671514

**Pull request merged**
