### PR TITLE
Generate the docs from the main dj-stripe repo

### PR DESCRIPTION
**Pull request by onekiloparsec**
As we all know, when there is little friction, dev is getting slower with time. Especially with documentation.

As dicussed [here](https://github.com/dj-stripe/dj-stripe/issues/1841), the docs of dj-stripe would be a lot easier to improve (and there are quite a lot to do) if it was consistently built from the main repo, yet keeping the style and configuration associated with this current .github.io repo.

This small PR is doing just that (hoping to close issue 1841 before updating content itself).

It is my first contribution to dj-stripe code (I am only an humble sponsor so far), and I amware there might be many different ways of doing it. But I tried to follow @jacklinke suggestion in the most straightforward manner.

Basically:

1. make room for a dynamic "docs" folder, then update the CI to:
2. clone the main dj-stripe repo
3. install all deps (including dj-stripe in development mode)
4. move up `docs/`, `tests/` and `mkdocs.yml` to the root folder to simulate their belonging to that current repo
5. generate docs and deploy identically as before.

I've chosen to make a PR from `master` to `master`, not knowing if something more sophisticated would be more appropriate for the people involved. I'd be happy to re-do anything you deem necessary.

Given the nature of the changes, I couldn't entirely test the whole thing of course. But I was at least able to generate the docs myself following the CI instructions as-is.

And Happy New Year. :-)

### CODE REVIEW

**Comment by onekiloparsec** [comment]
One thing is missing though: the trigger from the main `dj-stripe` repo.

**Comment by jleclanche** [comment]
Hi @onekiloparsec - Thanks for the PR!

I'm a little confused as to what the `old` folder is supposed to be after your PR, can you elaborate?

**Comment by onekiloparsec** [comment]
Nothing, I was just reluctant of deleting old content. Could be rentirely removed indeed (since it creates confusion).

**Comment by jleclanche** [comment]
Please do remove it instead of moving it. Old content is always in git.

**Comment by onekiloparsec** [comment]
@jleclanche are we good to go? :-)

**Comment by jleclanche** [comment]
Thank you! Sorry, super busy time here, low reactivity.

**Comment by onekiloparsec** [comment]
@jleclanche The latest action of deploy failed because of credentials issue. I'd be happy to follow up, but that's out of my hands.

Basically, I've imported the small piece of code from the `docs.yml` file of the main dj-stripe repo into this one:

```
      - name: Configure git user to make commit
        run: |
          git config user.name "dj-stripe commit bot"
          git config user.email "admin@djstripe.dev"
```

But I guess, this current repo has a slightly different configuration, and the credentials are not present in the settings. Hence the following `git clone` command in the `ci.yml` file fails.

These setup steps are always a bit of a pain. But once done, I'd be happy to contribute more freely in the documentation content itself.

**Comment by onekiloparsec** [comment]
@jleclanche or @kavdev or @arnav13081994 sorry to bother, but we miss by a tiny bit the possibility to overhaul the documentation. We just need to make sure the last build of this repo is working. Then we could have only one source of documentation, and easy to update through PRs.

Could you have a look? Thanks!

**Comment by jleclanche** [comment]
@onekiloparsec I tried to fix the CI build but getting this and I've no idea what it's trying to do / how to fix it.

```
Run poetry run mike set-default --push --rebase "${LATEST_STABLE_BRANCH##*/}"
error: version '2.7' does not exist
Error: Process completed with exit code 1.
```

I think mike is supposed to create a version if it doesn't exist. I dunno what was originally intended, it's been too long…

**Comment by onekiloparsec** [comment]
It's my fault. I didn't really realise the impact of importing a whole new `ci.yml` file... 

Of course, in _this_ repo, the branch `2.7` doesn't exist. I would remove thus the `--rebase` option (and we will have to think later how to get this number automatically).

Bottom line: here is new MR #3 and finger's crossed.

**Pull request merged**
